spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: "010"

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:123456}

loan:
  interest-rate: 2.5

bank:
  code: ${ADMIN_BANK_CODE:001}
  name: ${ADMIN_BANK_NAME:Quantum Banking S.A.}

admin:
  cpf: ${ADMIN_CPF:000.000.000-00}
  password: ${ADMIN_PASSWORD:root123}
  name: ${ADMIN_NAME:Admin}
  phone: ${ADMIN_PHONE:4004-0042}
  email: ${ADMIN_EMAIL:admin@quantumbank.com.br}

logging:
  level:
    org:
      springframework:
        cache: DEBUG